### ISSUE TITLE
关于HIFtool项目中的loader.py

### ISSUE THREAD

**Issue by tarxs** [Caoxuheng/FeafusFormer#1]
抱歉，刚刚想提问的是https://github.com/Caoxuheng/HIFtool/
这个项目中的代码，提问发错地方了，我没法删除，貌似作者可以把issue transfer到别的repo，或者你回答完后直接删除了。

问题：
我按照你论文中说的将loader.py中XionganDataset中的self.hsi_channel = 250，congfig里的也设置成250
却提示我
![image](https://github.com/Caoxuheng/FeafusFormer/assets/45535068/adf830c8-963e-4553-bfa4-e5e7818c4fe5)
检查了一下，Xiongantrain.npy的光谱维度是93，是否Xiongan数据集有问题，或者论文中给出的维度不对

**Comment by Caoxuheng** [comment]
目前，经反馈雄安数据集存在问题，这几天会重新上传一版。
雄安的数据集是正确的。在train中，测试部分被覆盖。
